//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveFeedUtility.LiveFeedServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://twingly.com/", ConfigurationName="LiveFeedServiceReference.LiveFeed2Soap")]
    public interface LiveFeed2Soap {
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://twingly.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://twingly.com/GetDataByPostCountAndTimespan", ReplyAction="*")]
        LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountAndTimespanResponse GetDataByPostCountAndTimespan(LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountAndTimespanRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://twingly.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://twingly.com/GetDataByPostCount", ReplyAction="*")]
        LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountResponse GetDataByPostCount(LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://twingly.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://twingly.com/GetDataByTimespan", ReplyAction="*")]
        LiveFeedUtility.LiveFeedServiceReference.GetDataByTimespanResponse GetDataByTimespan(LiveFeedUtility.LiveFeedServiceReference.GetDataByTimespanRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://twingly.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://twingly.com/GetData", ReplyAction="*")]
        LiveFeedUtility.LiveFeedServiceReference.GetDataResponse GetData(LiveFeedUtility.LiveFeedServiceReference.GetDataRequest request);
        
        // CODEGEN: Generating message contract since element name StatusResult from namespace http://twingly.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://twingly.com/Status", ReplyAction="*")]
        LiveFeedUtility.LiveFeedServiceReference.StatusResponse Status(LiveFeedUtility.LiveFeedServiceReference.StatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByPostCountAndTimespanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByPostCountAndTimespan", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountAndTimespanRequestBody Body;
        
        public GetDataByPostCountAndTimespanRequest() {
        }
        
        public GetDataByPostCountAndTimespanRequest(LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountAndTimespanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class GetDataByPostCountAndTimespanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime from;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime to;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int maxPosts;
        
        public GetDataByPostCountAndTimespanRequestBody() {
        }
        
        public GetDataByPostCountAndTimespanRequestBody(string apiKey, System.DateTime from, System.DateTime to, int maxPosts) {
            this.apiKey = apiKey;
            this.from = from;
            this.to = to;
            this.maxPosts = maxPosts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByPostCountAndTimespanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByPostCountAndTimespanResponse", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountAndTimespanResponseBody Body;
        
        public GetDataByPostCountAndTimespanResponse() {
        }
        
        public GetDataByPostCountAndTimespanResponse(LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountAndTimespanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class GetDataByPostCountAndTimespanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetDataByPostCountAndTimespanResult;
        
        public GetDataByPostCountAndTimespanResponseBody() {
        }
        
        public GetDataByPostCountAndTimespanResponseBody(System.Xml.XmlElement GetDataByPostCountAndTimespanResult) {
            this.GetDataByPostCountAndTimespanResult = GetDataByPostCountAndTimespanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByPostCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByPostCount", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountRequestBody Body;
        
        public GetDataByPostCountRequest() {
        }
        
        public GetDataByPostCountRequest(LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class GetDataByPostCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime timestamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int maxPosts;
        
        public GetDataByPostCountRequestBody() {
        }
        
        public GetDataByPostCountRequestBody(string apiKey, System.DateTime timestamp, int maxPosts) {
            this.apiKey = apiKey;
            this.timestamp = timestamp;
            this.maxPosts = maxPosts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByPostCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByPostCountResponse", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountResponseBody Body;
        
        public GetDataByPostCountResponse() {
        }
        
        public GetDataByPostCountResponse(LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class GetDataByPostCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetDataByPostCountResult;
        
        public GetDataByPostCountResponseBody() {
        }
        
        public GetDataByPostCountResponseBody(System.Xml.XmlElement GetDataByPostCountResult) {
            this.GetDataByPostCountResult = GetDataByPostCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByTimespanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByTimespan", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedUtility.LiveFeedServiceReference.GetDataByTimespanRequestBody Body;
        
        public GetDataByTimespanRequest() {
        }
        
        public GetDataByTimespanRequest(LiveFeedUtility.LiveFeedServiceReference.GetDataByTimespanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class GetDataByTimespanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime from;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime to;
        
        public GetDataByTimespanRequestBody() {
        }
        
        public GetDataByTimespanRequestBody(string apiKey, System.DateTime from, System.DateTime to) {
            this.apiKey = apiKey;
            this.from = from;
            this.to = to;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByTimespanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByTimespanResponse", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedUtility.LiveFeedServiceReference.GetDataByTimespanResponseBody Body;
        
        public GetDataByTimespanResponse() {
        }
        
        public GetDataByTimespanResponse(LiveFeedUtility.LiveFeedServiceReference.GetDataByTimespanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class GetDataByTimespanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetDataByTimespanResult;
        
        public GetDataByTimespanResponseBody() {
        }
        
        public GetDataByTimespanResponseBody(System.Xml.XmlElement GetDataByTimespanResult) {
            this.GetDataByTimespanResult = GetDataByTimespanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetData", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedUtility.LiveFeedServiceReference.GetDataRequestBody Body;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(LiveFeedUtility.LiveFeedServiceReference.GetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class GetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime timestamp;
        
        public GetDataRequestBody() {
        }
        
        public GetDataRequestBody(string apiKey, System.DateTime timestamp) {
            this.apiKey = apiKey;
            this.timestamp = timestamp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataResponse", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedUtility.LiveFeedServiceReference.GetDataResponseBody Body;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(LiveFeedUtility.LiveFeedServiceReference.GetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class GetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetDataResult;
        
        public GetDataResponseBody() {
        }
        
        public GetDataResponseBody(System.Xml.XmlElement GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Status", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedUtility.LiveFeedServiceReference.StatusRequestBody Body;
        
        public StatusRequest() {
        }
        
        public StatusRequest(LiveFeedUtility.LiveFeedServiceReference.StatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StatusRequestBody {
        
        public StatusRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatusResponse", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedUtility.LiveFeedServiceReference.StatusResponseBody Body;
        
        public StatusResponse() {
        }
        
        public StatusResponse(LiveFeedUtility.LiveFeedServiceReference.StatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class StatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StatusResult;
        
        public StatusResponseBody() {
        }
        
        public StatusResponseBody(string StatusResult) {
            this.StatusResult = StatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface LiveFeed2SoapChannel : LiveFeedUtility.LiveFeedServiceReference.LiveFeed2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LiveFeed2SoapClient : System.ServiceModel.ClientBase<LiveFeedUtility.LiveFeedServiceReference.LiveFeed2Soap>, LiveFeedUtility.LiveFeedServiceReference.LiveFeed2Soap {
        
        public LiveFeed2SoapClient() {
        }
        
        public LiveFeed2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LiveFeed2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiveFeed2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiveFeed2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountAndTimespanResponse LiveFeedUtility.LiveFeedServiceReference.LiveFeed2Soap.GetDataByPostCountAndTimespan(LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountAndTimespanRequest request) {
            return base.Channel.GetDataByPostCountAndTimespan(request);
        }
        
        public System.Xml.XmlElement GetDataByPostCountAndTimespan(string apiKey, System.DateTime from, System.DateTime to, int maxPosts) {
            LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountAndTimespanRequest inValue = new LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountAndTimespanRequest();
            inValue.Body = new LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountAndTimespanRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.maxPosts = maxPosts;
            LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountAndTimespanResponse retVal = ((LiveFeedUtility.LiveFeedServiceReference.LiveFeed2Soap)(this)).GetDataByPostCountAndTimespan(inValue);
            return retVal.Body.GetDataByPostCountAndTimespanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountResponse LiveFeedUtility.LiveFeedServiceReference.LiveFeed2Soap.GetDataByPostCount(LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountRequest request) {
            return base.Channel.GetDataByPostCount(request);
        }
        
        public System.Xml.XmlElement GetDataByPostCount(string apiKey, System.DateTime timestamp, int maxPosts) {
            LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountRequest inValue = new LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountRequest();
            inValue.Body = new LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.timestamp = timestamp;
            inValue.Body.maxPosts = maxPosts;
            LiveFeedUtility.LiveFeedServiceReference.GetDataByPostCountResponse retVal = ((LiveFeedUtility.LiveFeedServiceReference.LiveFeed2Soap)(this)).GetDataByPostCount(inValue);
            return retVal.Body.GetDataByPostCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiveFeedUtility.LiveFeedServiceReference.GetDataByTimespanResponse LiveFeedUtility.LiveFeedServiceReference.LiveFeed2Soap.GetDataByTimespan(LiveFeedUtility.LiveFeedServiceReference.GetDataByTimespanRequest request) {
            return base.Channel.GetDataByTimespan(request);
        }
        
        public System.Xml.XmlElement GetDataByTimespan(string apiKey, System.DateTime from, System.DateTime to) {
            LiveFeedUtility.LiveFeedServiceReference.GetDataByTimespanRequest inValue = new LiveFeedUtility.LiveFeedServiceReference.GetDataByTimespanRequest();
            inValue.Body = new LiveFeedUtility.LiveFeedServiceReference.GetDataByTimespanRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.from = from;
            inValue.Body.to = to;
            LiveFeedUtility.LiveFeedServiceReference.GetDataByTimespanResponse retVal = ((LiveFeedUtility.LiveFeedServiceReference.LiveFeed2Soap)(this)).GetDataByTimespan(inValue);
            return retVal.Body.GetDataByTimespanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiveFeedUtility.LiveFeedServiceReference.GetDataResponse LiveFeedUtility.LiveFeedServiceReference.LiveFeed2Soap.GetData(LiveFeedUtility.LiveFeedServiceReference.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public System.Xml.XmlElement GetData(string apiKey, System.DateTime timestamp) {
            LiveFeedUtility.LiveFeedServiceReference.GetDataRequest inValue = new LiveFeedUtility.LiveFeedServiceReference.GetDataRequest();
            inValue.Body = new LiveFeedUtility.LiveFeedServiceReference.GetDataRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.timestamp = timestamp;
            LiveFeedUtility.LiveFeedServiceReference.GetDataResponse retVal = ((LiveFeedUtility.LiveFeedServiceReference.LiveFeed2Soap)(this)).GetData(inValue);
            return retVal.Body.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiveFeedUtility.LiveFeedServiceReference.StatusResponse LiveFeedUtility.LiveFeedServiceReference.LiveFeed2Soap.Status(LiveFeedUtility.LiveFeedServiceReference.StatusRequest request) {
            return base.Channel.Status(request);
        }
        
        public string Status() {
            LiveFeedUtility.LiveFeedServiceReference.StatusRequest inValue = new LiveFeedUtility.LiveFeedServiceReference.StatusRequest();
            inValue.Body = new LiveFeedUtility.LiveFeedServiceReference.StatusRequestBody();
            LiveFeedUtility.LiveFeedServiceReference.StatusResponse retVal = ((LiveFeedUtility.LiveFeedServiceReference.LiveFeed2Soap)(this)).Status(inValue);
            return retVal.Body.StatusResult;
        }
    }
}
