//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveFeedExample.LiveFeedServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://twingly.com/", ConfigurationName="LiveFeedServiceReference.LiveFeed2Soap")]
    public interface LiveFeed2Soap {
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://twingly.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://twingly.com/GetDataByPostCountAndTimespan", ReplyAction="*")]
        LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountAndTimespanResponse GetDataByPostCountAndTimespan(LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountAndTimespanRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://twingly.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://twingly.com/GetDataByPostCount", ReplyAction="*")]
        LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountResponse GetDataByPostCount(LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://twingly.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://twingly.com/GetDataByTimespan", ReplyAction="*")]
        LiveFeedExample.LiveFeedServiceReference.GetDataByTimespanResponse GetDataByTimespan(LiveFeedExample.LiveFeedServiceReference.GetDataByTimespanRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://twingly.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://twingly.com/GetData", ReplyAction="*")]
        LiveFeedExample.LiveFeedServiceReference.GetDataResponse GetData(LiveFeedExample.LiveFeedServiceReference.GetDataRequest request);
        
        // CODEGEN: Generating message contract since element name StatusResult from namespace http://twingly.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://twingly.com/Status", ReplyAction="*")]
        LiveFeedExample.LiveFeedServiceReference.StatusResponse Status(LiveFeedExample.LiveFeedServiceReference.StatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByPostCountAndTimespanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByPostCountAndTimespan", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountAndTimespanRequestBody Body;
        
        public GetDataByPostCountAndTimespanRequest() {
        }
        
        public GetDataByPostCountAndTimespanRequest(LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountAndTimespanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class GetDataByPostCountAndTimespanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime from;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime to;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int maxPosts;
        
        public GetDataByPostCountAndTimespanRequestBody() {
        }
        
        public GetDataByPostCountAndTimespanRequestBody(string apiKey, System.DateTime from, System.DateTime to, int maxPosts) {
            this.apiKey = apiKey;
            this.from = from;
            this.to = to;
            this.maxPosts = maxPosts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByPostCountAndTimespanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByPostCountAndTimespanResponse", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountAndTimespanResponseBody Body;
        
        public GetDataByPostCountAndTimespanResponse() {
        }
        
        public GetDataByPostCountAndTimespanResponse(LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountAndTimespanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class GetDataByPostCountAndTimespanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetDataByPostCountAndTimespanResult;
        
        public GetDataByPostCountAndTimespanResponseBody() {
        }
        
        public GetDataByPostCountAndTimespanResponseBody(System.Xml.XmlElement GetDataByPostCountAndTimespanResult) {
            this.GetDataByPostCountAndTimespanResult = GetDataByPostCountAndTimespanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByPostCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByPostCount", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountRequestBody Body;
        
        public GetDataByPostCountRequest() {
        }
        
        public GetDataByPostCountRequest(LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class GetDataByPostCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime timestamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int maxPosts;
        
        public GetDataByPostCountRequestBody() {
        }
        
        public GetDataByPostCountRequestBody(string apiKey, System.DateTime timestamp, int maxPosts) {
            this.apiKey = apiKey;
            this.timestamp = timestamp;
            this.maxPosts = maxPosts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByPostCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByPostCountResponse", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountResponseBody Body;
        
        public GetDataByPostCountResponse() {
        }
        
        public GetDataByPostCountResponse(LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class GetDataByPostCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetDataByPostCountResult;
        
        public GetDataByPostCountResponseBody() {
        }
        
        public GetDataByPostCountResponseBody(System.Xml.XmlElement GetDataByPostCountResult) {
            this.GetDataByPostCountResult = GetDataByPostCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByTimespanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByTimespan", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedExample.LiveFeedServiceReference.GetDataByTimespanRequestBody Body;
        
        public GetDataByTimespanRequest() {
        }
        
        public GetDataByTimespanRequest(LiveFeedExample.LiveFeedServiceReference.GetDataByTimespanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class GetDataByTimespanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime from;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime to;
        
        public GetDataByTimespanRequestBody() {
        }
        
        public GetDataByTimespanRequestBody(string apiKey, System.DateTime from, System.DateTime to) {
            this.apiKey = apiKey;
            this.from = from;
            this.to = to;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataByTimespanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataByTimespanResponse", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedExample.LiveFeedServiceReference.GetDataByTimespanResponseBody Body;
        
        public GetDataByTimespanResponse() {
        }
        
        public GetDataByTimespanResponse(LiveFeedExample.LiveFeedServiceReference.GetDataByTimespanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class GetDataByTimespanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetDataByTimespanResult;
        
        public GetDataByTimespanResponseBody() {
        }
        
        public GetDataByTimespanResponseBody(System.Xml.XmlElement GetDataByTimespanResult) {
            this.GetDataByTimespanResult = GetDataByTimespanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetData", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedExample.LiveFeedServiceReference.GetDataRequestBody Body;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(LiveFeedExample.LiveFeedServiceReference.GetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class GetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime timestamp;
        
        public GetDataRequestBody() {
        }
        
        public GetDataRequestBody(string apiKey, System.DateTime timestamp) {
            this.apiKey = apiKey;
            this.timestamp = timestamp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataResponse", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedExample.LiveFeedServiceReference.GetDataResponseBody Body;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(LiveFeedExample.LiveFeedServiceReference.GetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class GetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetDataResult;
        
        public GetDataResponseBody() {
        }
        
        public GetDataResponseBody(System.Xml.XmlElement GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Status", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedExample.LiveFeedServiceReference.StatusRequestBody Body;
        
        public StatusRequest() {
        }
        
        public StatusRequest(LiveFeedExample.LiveFeedServiceReference.StatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StatusRequestBody {
        
        public StatusRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatusResponse", Namespace="http://twingly.com/", Order=0)]
        public LiveFeedExample.LiveFeedServiceReference.StatusResponseBody Body;
        
        public StatusResponse() {
        }
        
        public StatusResponse(LiveFeedExample.LiveFeedServiceReference.StatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://twingly.com/")]
    public partial class StatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StatusResult;
        
        public StatusResponseBody() {
        }
        
        public StatusResponseBody(string StatusResult) {
            this.StatusResult = StatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface LiveFeed2SoapChannel : LiveFeedExample.LiveFeedServiceReference.LiveFeed2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LiveFeed2SoapClient : System.ServiceModel.ClientBase<LiveFeedExample.LiveFeedServiceReference.LiveFeed2Soap>, LiveFeedExample.LiveFeedServiceReference.LiveFeed2Soap {
        
        public LiveFeed2SoapClient() {
        }
        
        public LiveFeed2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LiveFeed2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiveFeed2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiveFeed2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountAndTimespanResponse LiveFeedExample.LiveFeedServiceReference.LiveFeed2Soap.GetDataByPostCountAndTimespan(LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountAndTimespanRequest request) {
            return base.Channel.GetDataByPostCountAndTimespan(request);
        }
        
        public System.Xml.XmlElement GetDataByPostCountAndTimespan(string apiKey, System.DateTime from, System.DateTime to, int maxPosts) {
            LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountAndTimespanRequest inValue = new LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountAndTimespanRequest();
            inValue.Body = new LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountAndTimespanRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.maxPosts = maxPosts;
            LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountAndTimespanResponse retVal = ((LiveFeedExample.LiveFeedServiceReference.LiveFeed2Soap)(this)).GetDataByPostCountAndTimespan(inValue);
            return retVal.Body.GetDataByPostCountAndTimespanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountResponse LiveFeedExample.LiveFeedServiceReference.LiveFeed2Soap.GetDataByPostCount(LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountRequest request) {
            return base.Channel.GetDataByPostCount(request);
        }
        
        public System.Xml.XmlElement GetDataByPostCount(string apiKey, System.DateTime timestamp, int maxPosts) {
            LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountRequest inValue = new LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountRequest();
            inValue.Body = new LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.timestamp = timestamp;
            inValue.Body.maxPosts = maxPosts;
            LiveFeedExample.LiveFeedServiceReference.GetDataByPostCountResponse retVal = ((LiveFeedExample.LiveFeedServiceReference.LiveFeed2Soap)(this)).GetDataByPostCount(inValue);
            return retVal.Body.GetDataByPostCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiveFeedExample.LiveFeedServiceReference.GetDataByTimespanResponse LiveFeedExample.LiveFeedServiceReference.LiveFeed2Soap.GetDataByTimespan(LiveFeedExample.LiveFeedServiceReference.GetDataByTimespanRequest request) {
            return base.Channel.GetDataByTimespan(request);
        }
        
        public System.Xml.XmlElement GetDataByTimespan(string apiKey, System.DateTime from, System.DateTime to) {
            LiveFeedExample.LiveFeedServiceReference.GetDataByTimespanRequest inValue = new LiveFeedExample.LiveFeedServiceReference.GetDataByTimespanRequest();
            inValue.Body = new LiveFeedExample.LiveFeedServiceReference.GetDataByTimespanRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.from = from;
            inValue.Body.to = to;
            LiveFeedExample.LiveFeedServiceReference.GetDataByTimespanResponse retVal = ((LiveFeedExample.LiveFeedServiceReference.LiveFeed2Soap)(this)).GetDataByTimespan(inValue);
            return retVal.Body.GetDataByTimespanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiveFeedExample.LiveFeedServiceReference.GetDataResponse LiveFeedExample.LiveFeedServiceReference.LiveFeed2Soap.GetData(LiveFeedExample.LiveFeedServiceReference.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public System.Xml.XmlElement GetData(string apiKey, System.DateTime timestamp) {
            LiveFeedExample.LiveFeedServiceReference.GetDataRequest inValue = new LiveFeedExample.LiveFeedServiceReference.GetDataRequest();
            inValue.Body = new LiveFeedExample.LiveFeedServiceReference.GetDataRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.timestamp = timestamp;
            LiveFeedExample.LiveFeedServiceReference.GetDataResponse retVal = ((LiveFeedExample.LiveFeedServiceReference.LiveFeed2Soap)(this)).GetData(inValue);
            return retVal.Body.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LiveFeedExample.LiveFeedServiceReference.StatusResponse LiveFeedExample.LiveFeedServiceReference.LiveFeed2Soap.Status(LiveFeedExample.LiveFeedServiceReference.StatusRequest request) {
            return base.Channel.Status(request);
        }
        
        public string Status() {
            LiveFeedExample.LiveFeedServiceReference.StatusRequest inValue = new LiveFeedExample.LiveFeedServiceReference.StatusRequest();
            inValue.Body = new LiveFeedExample.LiveFeedServiceReference.StatusRequestBody();
            LiveFeedExample.LiveFeedServiceReference.StatusResponse retVal = ((LiveFeedExample.LiveFeedServiceReference.LiveFeed2Soap)(this)).Status(inValue);
            return retVal.Body.StatusResult;
        }
    }
}
